# Generated by Django 3.2.5 on 2021-07-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hos_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hos_kname', models.TextField()),
                ('hos_ename', models.TextField()),
            ],
            options={
                'db_table': 'hospital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HospitalDoctor',
            fields=[
                ('name', models.CharField(blank=True, db_column='name', max_length=10, null=True)),
                ('belong', models.CharField(blank=True, db_column='belong', max_length=20, null=True)),
                ('major', models.TextField(blank=True, db_column='major', null=True)),
                ('education', models.TextField(blank=True, db_column='education', null=True)),
                ('career', models.TextField(blank=True, db_column='career', null=True)),
                ('link', models.TextField(blank=True, db_column='link', null=True)),
                ('hos_id', models.CharField(db_column='hos_id', max_length=6)),
                ('doctor_id', models.CharField(db_column='doctor_id', max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'hospital_doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HospitalScholar',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', db_column='name', null=True)),
                ('belong', models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', db_column='belong', null=True)),
                ('pname', models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', db_column='pname', null=True)),
                ('jname', models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', db_column='jname', null=True)),
                ('jindex', models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', db_column='jindex', null=True)),
                ('year', models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', db_column='year', null=True)),
                ('citation', models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', db_column='citation', null=True)),
                ('coworker', models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', db_column='coworker', null=True)),
                ('hos_id', models.CharField(db_collation='utf8mb4_0900_ai_ci', db_column='hos_id', max_length=6)),
            ],
            options={
                'db_table': 'hospital_scholar',
                'managed': False,
            },
        ),
    ]
